# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qoh89ukv6nI8ZDsFa7rRNr7aeAyQWNY7
"""

import numpy as np

"""List vs Numpy - Time comparison

Numpy Arrays
"""

np.array([1,2,3,4])

np.zeros((4,5))

np.ones((4,5))

np.arange(1,16)

np.arange(0,17,2)

np.arange(1,17).reshape(4,4)

np.array([(1,2,3,4), (5,6,7,8)], dtype=int)

np.array([[1,2,3,4], [5,6,7,8]])

np.arange(0, 10000000)

np.array([(1,2,3,4,66), (5,6,7,8,99)]).shape

np.arange(0, 100).reshape(4,25).shape

"""Initial placeholders in numpy array"""

np.full((5,5), 25)

"""Create an identity matrix"""

np.eye(6)

"""Create a numpy array with random numbers


"""

np.random.random((5,6))

np.random.randint(1,100,(5,6))

"""Array of evenly spaced values"""

np.linspace(1,10,8)

np.linspace(0,30, 5, dtype=int)

"""Convert a list to a numpy array"""

list1 = [1,2,3,4,5]
a = np.asarray(list1)
print(a)
type(a)

"""Analysing a numpy array"""

c = np.random.randint(10, 90, (5,5))
print(c)

# array dimensions

print(c.shape)

# number of dimensions
print(c.ndim)

# number of elements in an array
print(c.size)

# checking the data type presented in an array
print(c.dtype)

"""Mathematical operations in np *arrays*"""

list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
print(list_1 + list_2)

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

print(a+b)

print(a-b)
print(a*b)
print(a/b)

