# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qoh89ukv6nI8ZDsFa7rRNr7aeAyQWNY7
"""

import numpy as np

"""List vs Numpy - Time comparison"""

from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

"""Numpy Arrays"""